const generateMainRoutesFile = () => {
  const docsShellRoutes = [
    '/docs',
    '/docs/${section}',
    '/docs/${section}/${page}',
    '/docs/${section}/${page}/${detail}'
  ];

  const lines = [];
  lines.push('// Auto-generated by parser/index.js. Do not edit manually.');
  lines.push('const routes = [');
  lines.push("  { path: '/', component: 'App' },");
  // Persistent component-testing harness route. Kept here (not derived from
  // markdown) so it survives every `docs:generate` regeneration of routes.js.
  lines.push("  { path: '/__test', component: 'TestHarness' },");
  // Hidden internal sandbox for hand-testing services (e.g. DragDropService).
  // Not in the navbar; kept here so it also survives `docs:generate`.
  lines.push("  { path: '/playground', component: 'Playground' },");
  // Game route — standalone 3D aim trainer
  lines.push("  { path: '/game', component: 'GamePage' },");
  docsShellRoutes.forEach((route) => {
    lines.push(`  { path: '${route.replace(/'/g, "\\'")}', component: 'App' },`);
  });
  lines.push("  { path: '/404', component: 'NotFound' }");
  lines.push('];');
  lines.push('');
  lines.push('export default routes;');
  lines.push('');

  return lines.join('\n');
};

export { generateMainRoutesFile };
