const normalizeRoute = (value) => {
  const route = String(value || '').trim();
  if (!route) return '';
  return route.startsWith('/') ? route : `/${route}`;
};

const uniqueDocsPaths = (entries) => {
  const set = new Set();
  (entries || []).forEach((entry) => {
    const route = normalizeRoute(entry?.route);
    if (!route.startsWith('/docs')) return;
    set.add(route);
  });
  return Array.from(set).sort((a, b) => a.localeCompare(b));
};

const generateMainRoutesFile = (entries) => {
  const docRoutes = uniqueDocsPaths(entries);
  const allRoutes = ['/docs', ...docRoutes];

  const docsFallbackRoutes = [
    '/docs/${section}',
    '/docs/${section}/${page}',
    '/docs/${section}/${page}/${detail}'
  ];

  docsFallbackRoutes.forEach((route) => {
    if (!allRoutes.includes(route)) {
      allRoutes.push(route);
    }
  });

  const lines = [];
  lines.push('// Auto-generated by parser/index.js. Do not edit manually.');
  lines.push('const routes = [');
  lines.push("  { path: '/', component: 'App' },");
  // Persistent component-testing harness route. Kept here (not derived from
  // markdown) so it survives every `docs:generate` regeneration of routes.js.
  lines.push("  { path: '/__test', component: 'TestHarness' },");
  allRoutes.forEach((route) => {
    lines.push(`  { path: '${route.replace(/'/g, "\\'")}', component: 'ComponentsPage' },`);
  });
  lines.push("  { path: '/404', component: 'NotFound' }");
  lines.push('];');
  lines.push('');
  lines.push('export default routes;');
  lines.push('');

  return lines.join('\n');
};

export { generateMainRoutesFile };
