const docsIndex = [
  {
    title: 'Table',
    route: '/docs/data/table',
    description: 'Table documentation with header and row rendering scenarios.',
    section: 'Data',
    group: 'Tables',
    order: 10,
    navLabel: 'Table',
    component: 'TableDocumentation',
    tags: ['table', 'data', 'display']
  },
  {
    title: 'Icon',
    route: '/docs/display/icon',
    description: 'Complete icon reference with all 291 symbols, usage patterns, and style variants.',
    section: 'Display',
    group: 'Basic',
    order: 20,
    navLabel: 'Icon',
    component: 'IconDocumentation',
    tags: ['icon', 'display', 'reference']
  },
  {
    title: 'CodeVisualizer',
    route: '/docs/display/code-visualizer',
    description: 'CodeVisualizer documentation with syntax highlighting and copy scenarios.',
    section: 'Display',
    group: 'Code',
    order: 10,
    navLabel: 'CodeVisualizer',
    component: 'CodeVisualizerDocumentation',
    tags: ['code', 'syntax', 'highlight', 'display']
  },
  {
    title: 'ToolTip',
    route: '/docs/display/tooltip',
    description: 'ToolTip documentation with hover, focus, placement, and delay scenarios.',
    section: 'Display',
    group: 'Overlay',
    order: 10,
    navLabel: 'ToolTip',
    component: 'ToolTipDocumentation',
    tags: ['tooltip', 'overlay', 'display']
  },
  {
    title: 'Toast',
    route: '/docs/feedback/toast',
    description: 'Toast notification component with type-based styling, auto-dismiss, and dismissable modes.',
    section: 'Feedback',
    group: 'Notifications',
    order: 10,
    navLabel: 'Toast',
    component: 'ToastDocumentation',
    tags: ['toast', 'notification', 'feedback', 'alert']
  },
  {
    title: 'Loading',
    route: '/docs/feedback/loading',
    description: 'Loading component documentation with activation and container usage scenarios.',
    section: 'Feedback',
    group: 'Status',
    order: 40,
    navLabel: 'Loading',
    component: 'LoadingDocumentation',
    tags: ['loading', 'feedback']
  },
  {
    title: 'Button',
    route: '/docs/input/button',
    description: 'Button documentation with executable prop scenarios.',
    section: 'Input Components',
    group: 'Basic',
    order: 10,
    navLabel: 'Button',
    component: 'ButtonDocumentation',
    tags: ['button', 'input']
  },
  {
    title: 'Input',
    route: '/docs/input/input',
    description: 'Input component documentation with practical setup examples.',
    section: 'Input Components',
    group: 'Basic',
    order: 11,
    navLabel: 'Input',
    component: 'InputDocumentation',
    tags: ['input', 'forms']
  },
  {
    title: 'Select',
    route: '/docs/input/select',
    description: 'Select component documentation with practical setup examples.',
    section: 'Input Components',
    group: 'Basic',
    order: 12,
    navLabel: 'Select',
    component: 'SelectDocumentation',
    tags: ['select', 'forms']
  },
  {
    title: 'Checkbox',
    route: '/docs/input/checkbox',
    description: 'Checkbox component documentation with practical prop scenarios.',
    section: 'Input Components',
    group: 'Basic',
    order: 13,
    navLabel: 'Checkbox',
    component: 'CheckboxDocumentation',
    tags: ['checkbox', 'input', 'forms']
  },
  {
    title: 'Switch',
    route: '/docs/input/switch',
    description: 'Switch component documentation with practical interaction scenarios.',
    section: 'Input Components',
    group: 'Basic',
    order: 14,
    navLabel: 'Switch',
    component: 'SwitchDocumentation',
    tags: ['switch', 'input', 'toggle']
  },
  {
    title: 'Markdown Parser Rules',
    route: '/docs/internal/markdown-parser-rules',
    description: 'Contract, template, and generation rules for Slice.js documentation pages.',
    section: 'Internal',
    group: 'Documentation',
    order: 1,
    navLabel: 'Parser Rules',
    component: 'MarkdownParserRulesDocumentation',
    tags: ['docs', 'parser', 'rules']
  },
  {
    title: 'Layout',
    route: '/docs/layout/layout',
    description: 'Layout container documentation with view swapping scenarios.',
    section: 'Layout',
    group: 'Containers',
    order: 10,
    navLabel: 'Layout',
    component: 'LayoutDocumentation',
    tags: ['layout', 'container']
  },
  {
    title: 'Card',
    route: '/docs/layout/card',
    description: 'Card documentation with prop scenario scripts.',
    section: 'Layout',
    group: 'Containers',
    order: 20,
    navLabel: 'Card',
    component: 'CardDocumentation',
    tags: ['card', 'layout']
  },
  {
    title: 'Details',
    route: '/docs/layout/details',
    description: 'Details component documentation with collapsible content scenarios.',
    section: 'Layout',
    group: 'Containers',
    order: 21,
    navLabel: 'Details',
    component: 'DetailsDocumentation',
    tags: ['details', 'disclosure', 'layout']
  },
  {
    title: 'Grid',
    route: '/docs/layout/grid',
    description: 'Grid component documentation with layout composition scenarios.',
    section: 'Layout',
    group: 'Containers',
    order: 22,
    navLabel: 'Grid',
    component: 'GridDocumentation',
    tags: ['grid', 'layout']
  },
  {
    title: 'ElementCarrousel',
    route: '/docs/layout/element-carrousel',
    description: 'ElementCarrousel documentation with slide navigation and indicator scenarios.',
    section: 'Layout',
    group: 'Containers',
    order: 25,
    navLabel: 'Carrousel',
    component: 'ElementCarrouselDocumentation',
    tags: ['carrousel', 'carousel', 'layout', 'navigation']
  },
  {
    title: 'Navbar',
    route: '/docs/navigation/navbar',
    description: 'Navbar component documentation with practical setup examples.',
    section: 'Navigation',
    group: 'Core',
    order: 30,
    navLabel: 'Navbar',
    component: 'NavbarDocumentation',
    tags: ['navbar', 'navigation']
  },
  {
    title: 'Tabs',
    route: '/docs/navigation/tabs',
    description: 'Deep Tabs documentation with behavior-first scenarios and integration patterns.',
    section: 'Navigation',
    group: 'Core',
    order: 31,
    navLabel: 'Tabs',
    component: 'TabsDocumentation',
    tags: ['tabs', 'navigation', 'routing']
  },
  {
    title: 'DropDown',
    route: '/docs/navigation/dropdown',
    description: 'DropDown component documentation with practical navigation scenarios.',
    section: 'Navigation',
    group: 'Core',
    order: 32,
    navLabel: 'DropDown',
    component: 'DropDownDocumentation',
    tags: ['dropdown', 'navigation']
  },
  {
    title: 'BottomNav',
    route: '/docs/navigation/bottom-nav',
    description: 'BottomNav (floating bottom tab bar) documentation with practical navigation scenarios.',
    section: 'Navigation',
    group: 'Core',
    order: 33,
    navLabel: 'BottomNav',
    component: 'BottomNavDocumentation',
    tags: ['bottomnav', 'navigation', 'tabs', 'mobile']
  },
  {
    title: 'Breadcrumbs',
    route: '/docs/navigation/breadcrumbs',
    description: 'Breadcrumbs component for hierarchical navigation context and quick backtracking.',
    section: 'Navigation',
    group: 'Core',
    order: 34,
    navLabel: 'Breadcrumbs',
    component: 'BreadcrumbsDocumentation',
    tags: ['breadcrumbs', 'navigation', 'hierarchy']
  },
  {
    title: 'NotFound',
    route: '/docs/navigation/not-found',
    description: 'NotFound 404 page documentation with route fallback scenarios.',
    section: 'Navigation',
    group: 'Core',
    order: 40,
    navLabel: 'NotFound',
    component: 'NotFoundDocumentation',
    tags: ['not-found', '404', 'navigation', 'routing']
  },
  {
    title: 'TreeView',
    route: '/docs/navigation/treeview',
    description: 'TreeView documentation with nested item and navigation scenarios.',
    section: 'Navigation',
    group: 'Navigation',
    order: 50,
    navLabel: 'TreeView',
    component: 'TreeViewDocumentation',
    tags: ['treeview', 'navigation', 'tree']
  },
  {
    title: 'Route',
    route: '/docs/routing/route',
    description: 'Route container documentation with dynamic path and metadata scenarios.',
    section: 'Routing',
    group: 'Containers',
    order: 50,
    navLabel: 'Route',
    component: 'RouteDocumentation',
    tags: ['route', 'routing', 'container']
  },
  {
    title: 'MultiRoute',
    route: '/docs/routing/multi-route',
    description: 'MultiRoute container documentation with app-shell and dynamic route scenarios.',
    section: 'Routing',
    group: 'Containers',
    order: 51,
    navLabel: 'MultiRoute',
    component: 'MultiRouteDocumentation',
    tags: ['multiroute', 'routing', 'app-shell']
  },
  {
    title: 'ToastProvider',
    route: '/docs/services/toast-provider',
    description: 'Singleton service for programmatic toast management — show, dismiss, clear, and position notifications.',
    section: 'Services',
    group: 'Feedback',
    order: 50,
    navLabel: 'ToastProvider',
    component: 'ToastProviderDocumentation',
    tags: ['toast', 'provider', 'service', 'notification']
  },
  {
    title: 'FetchManager',
    route: '/docs/services/fetch-manager',
    description: 'HTTP client Service over fetch with timeout, base URL, default headers and Loading integration.',
    section: 'Services',
    group: 'Networking',
    order: 30,
    navLabel: 'FetchManager',
    component: 'FetchManagerDocumentation',
    tags: ['service', 'fetch', 'http', 'networking']
  },
  {
    title: 'ToolTipProvider',
    route: '/docs/services/tooltip-provider',
    description: 'Lightweight singleton Service for efficient tooltip management via programmatic and data-attribute APIs.',
    section: 'Services',
    group: 'Overlay',
    order: 15,
    navLabel: 'ToolTipProvider',
    component: 'ToolTipProviderDocumentation',
    tags: ['tooltip', 'provider', 'service', 'overlay']
  },
  {
    title: 'LocalStorageManager',
    route: '/docs/services/local-storage-manager',
    description: 'Service wrapper over window.localStorage with automatic JSON serialization.',
    section: 'Services',
    group: 'Storage',
    order: 10,
    navLabel: 'LocalStorageManager',
    component: 'LocalStorageManagerDocumentation',
    tags: ['service', 'storage', 'localstorage']
  },
  {
    title: 'IndexedDbManager',
    route: '/docs/services/indexed-db-manager',
    description: 'Async Service wrapper over IndexedDB for a single auto-keyed object store.',
    section: 'Services',
    group: 'Storage',
    order: 20,
    navLabel: 'IndexedDbManager',
    component: 'IndexedDbManagerDocumentation',
    tags: ['service', 'storage', 'indexeddb']
  },
  {
    title: 'MiniInspector',
    route: '/docs/utilities/mini-inspector',
    description: 'MiniInspector documentation with executable live-editing scenarios.',
    section: 'Utilities',
    group: 'Developer',
    order: 10,
    navLabel: 'MiniInspector',
    component: 'MiniInspectorDocumentation',
    tags: ['inspector', 'devtools', 'props', 'setters']
  },
];

export default docsIndex;
