const components = {
  "App": "AppComponents",
  "Button": "Visual",
  "ButtonDocumentation": "DocumentationPages",
  "Card": "Visual",
  "CardDocumentation": "DocumentationPages",
  "Checkbox": "Visual",
  "CodeVisualizer": "Visual",
  "ComponentsPage": "AppComponents",
  "CopyMarkdownMenu": "AppComponents",
  "Details": "Visual",
  "DocumentationLibraryHome": "DocumentationPages",
  "DropDown": "Visual",
  "FetchManager": "Service",
  "Grid": "Visual",
  "Icon": "Visual",
  "IndexedDbManager": "Service",
  "Input": "Visual",
  "InputDocumentation": "DocumentationPages",
  "Layout": "Visual",
  "Link": "Service",
  "Loading": "Visual",
  "LocalStorageManager": "Service",
  "MainMenu": "AppComponents",
  "MarkdownParserRulesDocumentation": "DocumentationPages",
  "MultiRoute": "Visual",
  "MyNavigation": "AppComponents",
  "Navbar": "Visual",
  "NavbarDocumentation": "DocumentationPages",
  "NotFound": "Visual",
  "Route": "Visual",
  "Select": "Visual",
  "SelectDocumentation": "DocumentationPages",
  "Switch": "Visual",
  "Table": "Visual",
  "TabsDocumentation": "DocumentationPages",
  "Translator": "Service",
  "TreeItem": "Visual",
  "TreeView": "Visual",
  "VisualLibraryHome": "AppComponents"
};

export default components;
