// Auto-generated by parser/index.js. Do not edit manually.
const routes = [
  { path: '/', component: 'App' },
  { path: '/__test', component: 'TestHarness' },
  { path: '/playground', component: 'Playground' },
  { path: '/game', component: 'GamePage' },
  { path: '/docs', component: 'App' },
  { path: '/docs/${section}', component: 'App' },
  { path: '/docs/${section}/${page}', component: 'App' },
  { path: '/docs/${section}/${page}/${detail}', component: 'App' },
  { path: '/404', component: 'NotFound' }
];

export default routes;
