/* Auto-generated by slice types generate. Do not edit manually. */

export interface AppProps {
  [key: string]: unknown;
}

export interface ButtonProps {
  [key: string]: unknown;
  customColor?: Record<string, unknown>;
  icon?: Record<string, unknown>;
  onClickCallback?: (...args: unknown[]) => unknown;
  value?: string;
}

export interface ButtonDocumentationProps {
  [key: string]: unknown;
}

export interface CardProps {
  [key: string]: unknown;
  actions?: unknown[];
  badge?: string;
  customColor?: Record<string, unknown>;
  details?: string;
  disabled?: boolean;
  icon?: Record<string, unknown>;
  image?: string;
  interactive?: boolean;
  isOpen?: boolean;
  loading?: boolean;
  onClick?: (...args: unknown[]) => unknown;
  text?: string;
  title?: string;
  variant?: 'default' | 'elevated' | 'outlined' | 'minimal';
}

export interface CardDocumentationProps {
  [key: string]: unknown;
}

export interface CheckboxProps {
  [key: string]: unknown;
  checked?: boolean;
  customColor?: string;
  disabled?: boolean;
  label?: string;
  labelPlacement?: string;
}

export interface CheckboxDocumentationProps {
  [key: string]: unknown;
}

export interface CodeVisualizerProps {
  [key: string]: unknown;
}

export interface CodeVisualizerDocumentationProps {
  [key: string]: unknown;
}

export interface ComponentShowcaseProps {
  [key: string]: unknown;
  badgeLabel?: string;
  title?: string;
  variants?: unknown[];
}

export interface ComponentsPageProps {
  [key: string]: unknown;
}

export interface CopyMarkdownMenuProps {
  [key: string]: unknown;
  label?: string;
  markdownContent?: string;
  markdownPath?: string;
}

export interface DemoBoxProps {
  [key: string]: unknown;
  expected?: string;
  label?: string;
}

export interface DemoRouteDetailsProps {
  [key: string]: unknown;
}

export interface DemoRouteHomeProps {
  [key: string]: unknown;
}

export interface DemoRouteStateProps {
  [key: string]: unknown;
}

export interface DetailsProps {
  [key: string]: unknown;
  text?: string;
  title?: string;
}

export interface DetailsDocumentationProps {
  [key: string]: unknown;
}

export interface DocumentationLibraryHomeProps {
  [key: string]: unknown;
}

export interface DropDownProps {
  [key: string]: unknown;
  label?: string;
  options?: unknown[];
}

export interface DropDownDocumentationProps {
  [key: string]: unknown;
}

export interface ElementCarrouselProps {
  [key: string]: unknown;
  elements?: unknown[];
}

export interface ElementCarrouselDocumentationProps {
  [key: string]: unknown;
}

export interface FetchManagerProps {
  [key: string]: unknown;
}

export interface GridProps {
  [key: string]: unknown;
  columns?: number;
  columnTemplate?: string;
  gap?: string;
  items?: unknown[];
  rows?: number;
  rowTemplate?: string;
}

export interface GridDocumentationProps {
  [key: string]: unknown;
}

export interface IconProps {
  [key: string]: unknown;
  color?: string;
  iconStyle?: string;
  name?: string;
  size?: string;
}

export interface IconDocumentationProps {
  [key: string]: unknown;
}

export interface IndexedDbManagerProps {
  [key: string]: unknown;
}

export interface InputProps {
  [key: string]: unknown;
  conditions?: Record<string, unknown>;
  disabled?: boolean;
  placeholder?: string;
  required?: boolean;
  secret?: boolean;
  type?: string;
  value?: string;
}

export interface InputDocumentationProps {
  [key: string]: unknown;
}

export interface LayoutProps {
  [key: string]: unknown;
  layout?: Record<string, unknown>;
  view?: Record<string, unknown>;
}

export interface LayoutDocumentationProps {
  [key: string]: unknown;
}

export interface LinkProps {
  [key: string]: unknown;
}

export interface LoadingProps {
  [key: string]: unknown;
  container?: Record<string, unknown>;
  isActive?: boolean;
}

export interface LoadingDocumentationProps {
  [key: string]: unknown;
}

export interface LocalStorageManagerProps {
  [key: string]: unknown;
}

export interface MainMenuProps {
  [key: string]: unknown;
}

export interface MarkdownParserRulesDocumentationProps {
  [key: string]: unknown;
}

export interface MultiRouteProps {
  [key: string]: unknown;
}

export interface MultiRouteDocumentationProps {
  [key: string]: unknown;
}

export interface MyNavigationProps {
  [key: string]: unknown;
}

export interface NavbarProps {
  [key: string]: unknown;
  buttons?: unknown[];
  direction?: string;
  items?: unknown[];
  logo?: Record<string, unknown>;
  position?: string;
}

export interface NavbarDocumentationProps {
  [key: string]: unknown;
}

export interface NotFoundProps {
  [key: string]: unknown;
}

export interface NotFoundDocumentationProps {
  [key: string]: unknown;
}

export interface PropsTableProps {
  [key: string]: unknown;
  props?: unknown[];
}

export interface RouteProps {
  [key: string]: unknown;
}

export interface RouteDocumentationProps {
  [key: string]: unknown;
}

export interface SelectProps {
  [key: string]: unknown;
  disabled?: boolean;
  label?: string;
  multiple?: boolean;
  onOptionSelect?: (...args: unknown[]) => unknown;
  options?: unknown[];
  visibleProp?: string;
}

export interface SelectDocumentationProps {
  [key: string]: unknown;
}

export interface SwitchProps {
  [key: string]: unknown;
  checked?: boolean;
  customColor?: string;
  disabled?: boolean;
  label?: string;
  labelPlacement?: string;
  toggle?: (...args: unknown[]) => unknown;
}

export interface SwitchDocumentationProps {
  [key: string]: unknown;
}

export interface TableProps {
  [key: string]: unknown;
  headers?: unknown[];
  rows?: unknown[];
}

export interface TableDocumentationProps {
  [key: string]: unknown;
}

export interface TabsProps {
  [key: string]: unknown;
  activeTab?: string;
  items?: { id: string; label: string; }[];
  onTabChange?: (...args: unknown[]) => unknown;
}

export interface TabsDocumentationProps {
  [key: string]: unknown;
}

export interface ThemeSelectorProps {
  [key: string]: unknown;
}

export interface ToolTipProps {
  [key: string]: unknown;
  text?: string;
}

export interface ToolTipDocumentationProps {
  [key: string]: unknown;
}

export interface TreeItemProps {
  [key: string]: unknown;
  items?: unknown[];
  onClickCallback?: (...args: unknown[]) => unknown;
  path?: string;
  value?: string;
}

export interface TreeViewProps {
  [key: string]: unknown;
  items?: unknown[];
  onClickCallback?: (...args: unknown[]) => unknown;
}

export interface TreeViewDocumentationProps {
  [key: string]: unknown;
}

export interface VisualLibraryHomeProps {
  [key: string]: unknown;
}

export interface SliceComponentPropsMap {
  App: AppProps;
  Button: ButtonProps;
  ButtonDocumentation: ButtonDocumentationProps;
  Card: CardProps;
  CardDocumentation: CardDocumentationProps;
  Checkbox: CheckboxProps;
  CheckboxDocumentation: CheckboxDocumentationProps;
  CodeVisualizer: CodeVisualizerProps;
  CodeVisualizerDocumentation: CodeVisualizerDocumentationProps;
  ComponentShowcase: ComponentShowcaseProps;
  ComponentsPage: ComponentsPageProps;
  CopyMarkdownMenu: CopyMarkdownMenuProps;
  DemoBox: DemoBoxProps;
  DemoRouteDetails: DemoRouteDetailsProps;
  DemoRouteHome: DemoRouteHomeProps;
  DemoRouteState: DemoRouteStateProps;
  Details: DetailsProps;
  DetailsDocumentation: DetailsDocumentationProps;
  DocumentationLibraryHome: DocumentationLibraryHomeProps;
  DropDown: DropDownProps;
  DropDownDocumentation: DropDownDocumentationProps;
  ElementCarrousel: ElementCarrouselProps;
  ElementCarrouselDocumentation: ElementCarrouselDocumentationProps;
  FetchManager: FetchManagerProps;
  Grid: GridProps;
  GridDocumentation: GridDocumentationProps;
  Icon: IconProps;
  IconDocumentation: IconDocumentationProps;
  IndexedDbManager: IndexedDbManagerProps;
  Input: InputProps;
  InputDocumentation: InputDocumentationProps;
  Layout: LayoutProps;
  LayoutDocumentation: LayoutDocumentationProps;
  Link: LinkProps;
  Loading: LoadingProps;
  LoadingDocumentation: LoadingDocumentationProps;
  LocalStorageManager: LocalStorageManagerProps;
  MainMenu: MainMenuProps;
  MarkdownParserRulesDocumentation: MarkdownParserRulesDocumentationProps;
  MultiRoute: MultiRouteProps;
  MultiRouteDocumentation: MultiRouteDocumentationProps;
  MyNavigation: MyNavigationProps;
  Navbar: NavbarProps;
  NavbarDocumentation: NavbarDocumentationProps;
  NotFound: NotFoundProps;
  NotFoundDocumentation: NotFoundDocumentationProps;
  PropsTable: PropsTableProps;
  Route: RouteProps;
  RouteDocumentation: RouteDocumentationProps;
  Select: SelectProps;
  SelectDocumentation: SelectDocumentationProps;
  Switch: SwitchProps;
  SwitchDocumentation: SwitchDocumentationProps;
  Table: TableProps;
  TableDocumentation: TableDocumentationProps;
  Tabs: TabsProps;
  TabsDocumentation: TabsDocumentationProps;
  ThemeSelector: ThemeSelectorProps;
  ToolTip: ToolTipProps;
  ToolTipDocumentation: ToolTipDocumentationProps;
  TreeItem: TreeItemProps;
  TreeView: TreeViewProps;
  TreeViewDocumentation: TreeViewDocumentationProps;
  VisualLibraryHome: VisualLibraryHomeProps;
}

export type SliceComponentName = keyof SliceComponentPropsMap;
export type SliceDynamicElement = HTMLElement & Record<string, any>;

declare global {
  const slice: SliceBuildApi & Record<string, any>;

  interface Event {
    detail: any;
    key: any;
    request: any;
    waitUntil: any;
    respondWith: any;
    target: any;
    currentTarget: any;
  }

  interface Element {
    querySelector<E extends Element = HTMLElement>(selectors: string): E | null;
    querySelectorAll<E extends Element = HTMLElement>(selectors: string): NodeListOf<E>;
  }
  interface HTMLElement {
    [key: string]: any;
  }
  interface EventTarget {
    [key: string]: any;
  }

  interface SliceBuildApi {
    build<K extends SliceComponentName>(
      name: K,
      props?: SliceComponentPropsMap[K]
    ): Promise<SliceDynamicElement | null>;
  }
}

declare module 'slicejs-web-framework' {
  interface SliceApi {
    build<K extends SliceComponentName>(
      name: K,
      props?: SliceComponentPropsMap[K]
    ): Promise<SliceDynamicElement | null>;
    getComponent<T extends SliceDynamicElement = SliceDynamicElement>(
      componentSliceId: string
    ): T | undefined;
  }
}

export {};
